// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA1QZHyGHv2vfXb7iKH0LwGHlIV-3_-5k',
    appId: '1:351519301946:web:31538e080e5d835e59f003',
    messagingSenderId: '351519301946',
    projectId: 'flutter-camera-413de',
    authDomain: 'flutter-camera-413de.firebaseapp.com',
    storageBucket: 'flutter-camera-413de.appspot.com',
    measurementId: 'G-2YXGS3N248',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtaCr374J5_2foBxhEy32S1IIPaQGey5U',
    appId: '1:351519301946:android:8ffebc041c61267159f003',
    messagingSenderId: '351519301946',
    projectId: 'flutter-camera-413de',
    storageBucket: 'flutter-camera-413de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpYeK64bQ6Wy8u8GhM93SSabg5hte_xw',
    appId: '1:351519301946:ios:cb6b3569861a36f659f003',
    messagingSenderId: '351519301946',
    projectId: 'flutter-camera-413de',
    storageBucket: 'flutter-camera-413de.appspot.com',
    iosClientId: '351519301946-cecnk29l6l744vhbceee76ff8537fl27.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpYeK64bQ6Wy8u8GhM93SSabg5hte_xw',
    appId: '1:351519301946:ios:a0156b9aa433756259f003',
    messagingSenderId: '351519301946',
    projectId: 'flutter-camera-413de',
    storageBucket: 'flutter-camera-413de.appspot.com',
    iosClientId: '351519301946-029agquhs9poc1fbsp22b8vo3ed4htms.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCamera.RunnerTests',
  );
}
